// Toutes les phrases dites par l'appli. Identifiant -> texte.
// Les MP3 sont générés à partir de ce fichier (outils/generer_audio.py).
// Les nombres sont écrits en LETTRES pour que la voix les lise correctement.
// Toute modification d'un texte impose de régénérer l'audio.
export const PHRASES = {
  // --- Accueil ---
  qui_joue: "Qui joue aujourd'hui ? Touche ton image.",
  bonjour_koala: "Bonjour petit koala !",
  bonjour_panda: "Bonjour petit panda !",
  bonjour_licorne: "Bonjour petite licorne !",
  bonjour_chiot: "Bonjour petit chiot !",
  accueil_test: "Aujourd'hui, on fait le grand jeu de départ. Touche le bouton vert pour commencer.",
  accueil_reprise: "Ton jeu t'attend. Touche le bouton vert pour continuer.",
  accueil_fini: "Tu as fini le grand jeu de départ. Bravo ! Les prochains jeux arrivent bientôt.",

  // --- Test : cadre ---
  test_intro: "On va faire un petit jeu, pour voir tout ce que tu sais déjà. Écoute bien chaque question. Prends ton temps : ce n'est pas une course. Si tu veux réécouter, touche l'oreille.",
  test_reprise: "On reprend là où on s'était arrêtés.",
  test_pause: "On fait une pause. À tout à l'heure !",
  test_fin: "Bravo, le jeu est fini ! Tu as très bien travaillé. Tu peux aller le dire à un grand.",

  // --- Retours (règle B5 : neutres sur l'erreur, valorisants sur la démarche) ---
  verifie: "Hum… vérifie bien. Regarde encore, et essaie une autre fois.",
  bravo_1: "Bravo !",
  bravo_2: "Très bien !",
  bravo_3: "Oui, c'est ça !",
  bravo_verifie: "Bravo, tu as vérifié, et tu as trouvé !",
  aide_intro: "Ce n'est pas grave. Regarde, je t'explique.",
  suivant: "Touche la flèche pour continuer.",

  // --- Items du test de positionnement (T1) ---
  i01_c: "Regarde bien. Combien y en a-t-il ? Tape le nombre, puis touche le bouton vert.",
  i01_e: "Il y en a cinq, comme sur un dé.",
  i02_c: "Compte bien. Combien y en a-t-il en tout ?",
  i02_e: "Il y en a quatorze. Pour bien compter, on touche chaque image une seule fois.",
  i03_c: "Quel nombre vient juste après trente-neuf ?",
  i03_e: "Après trente-neuf, il y a quarante.",
  i04_c: "Quel nombre vient juste après quatre-vingt-neuf ?",
  i04_e: "Après quatre-vingt-neuf, il y a quatre-vingt-dix.",
  i05_c: "Chaque grande barre a dix cubes. Combien y a-t-il de cubes en tout ?",
  i05_e: "Quatre barres de dix, ça fait quarante. Plus sept petits cubes : quarante-sept.",
  i06_c: "Montre le nombre cinquante-trois, avec des barres de dix et des petits cubes. Puis touche le bouton vert.",
  i06_e: "Cinquante-trois, c'est cinq barres de dix, et trois petits cubes.",
  i07_c: "Touche le nombre le plus grand.",
  i07_e: "Le plus grand, c'est quatre-vingt-trois : il a huit dizaines. Trente-huit n'en a que trois.",
  i08_c: "Voici une ligne qui va de zéro à cent. Touche l'endroit où se trouve cinquante.",
  i08_e: "Cinquante est juste au milieu, entre zéro et cent.",
  i09_c: "Six, plus combien, égale dix ?",
  i09_e: "Six plus quatre égale dix. Regarde : il manque quatre cases pour remplir la boîte.",
  i10_c: "Huit, c'est cinq plus combien ?",
  i10_e: "Huit, c'est cinq plus trois.",
  i11_c: "Combien font six plus trois ?",
  i11_e: "Six plus trois égale neuf.",
  i12_c: "Tu as cinq billes. On t'en donne trois de plus. Combien de billes as-tu maintenant ?",
  i12_e: "Cinq billes, plus trois billes : ça fait huit billes.",
  i13_c: "Tu as neuf bonbons. Tu en manges trois. Combien de bonbons te reste-t-il ?",
  i13_e: "Neuf bonbons, moins les trois que tu as mangés : il en reste six.",
  i14_c: "Tom a sept cartes. Léa a trois cartes de plus que Tom. Combien de cartes a Léa ?",
  i14_e: "Léa a trois cartes de plus que Tom : sept plus trois, ça fait dix cartes.",
  i15_c: "Écoute bien : deux… quatre… six… Quel nombre vient après ?",
  i15_e: "On avance de deux en deux : deux, quatre, six, huit.",

  // --- Séances d'entraînement : cadre ---
  accueil_seance: "Ton jeu du jour t'attend. Touche le bouton vert pour commencer.",
  seance_intro: "C'est parti pour le jeu du jour. Écoute bien chaque question, et prends ton temps. Si tu ne comprends pas, touche le point d'interrogation : je t'explique.",
  ne_sait_pas: "D'accord. Tu as bien fait de le dire. Regarde, je t'explique.",
  accueil_tout_fini: "Tu as fini tous les jeux. Bravo ! Les prochains jeux arrivent bientôt.",
  seance_fin: "Bravo, le jeu du jour est fini ! Tu as bien réfléchi. Tu peux aller le dire à un grand.",

  // --- Parcours C, séance 1 ---
  c1_01_c: "Regarde la boîte. Combien de cases sont pleines ?",
  c1_01_e: "Une ligne de cinq, et encore deux : six, sept. Il y a sept cases pleines.",
  c1_02_c: "Il faut cinq bonbons. Il y en a déjà trois. Combien en manque-t-il ?",
  c1_02_e: "Trois bonbons, plus deux bonbons, ça fait cinq. Il en manque deux.",
  c1_03_c: "Il faut six étoiles. Il y en a déjà quatre. Combien en manque-t-il ?",
  c1_03_e: "Quatre étoiles, plus deux étoiles, ça fait six. Il en manque deux.",
  c1_04_c: "Chaque grande barre a dix cubes. Compte d'abord les barres, de dix en dix, puis les petits cubes. Combien y a-t-il de cubes en tout ?",
  c1_04_e: "Dix, vingt : deux barres. Puis vingt et un, vingt-deux, vingt-trois, vingt-quatre. Il y a vingt-quatre cubes.",
  c1_05_c: "Il faut sept billes. Il y en a déjà quatre. Combien en manque-t-il ?",
  c1_05_e: "Quatre billes, plus trois billes, ça fait sept. Il en manque trois.",
  c1_06_c: "Combien font cinq plus deux ?",
  c1_06_e: "Cinq, et encore deux : six, sept. Cinq plus deux égale sept.",
  c1_07_c: "Combien y a-t-il de cubes en tout ? Compte d'abord les barres de dix.",
  c1_07_e: "Dix, vingt, trente : trois barres. Plus cinq petits cubes : trente-cinq.",
  c1_08_c: "On veut cinq images. On en a déjà quatre. Combien faut-il en ajouter ?",
  c1_08_e: "Quatre, et encore un : cinq. Il faut en ajouter un. Quatre plus un égale cinq.",
  c1_09_c: "Écoute : quatre-vingt-sept, quatre-vingt-huit, quatre-vingt-neuf… Quel nombre vient après ? Tape-le.",
  c1_09_e: "Après quatre-vingt-neuf, il y a quatre-vingt-dix. On écrit le chiffre neuf, puis le chiffre zéro : neuf barres de dix.",
  c1_10_c: "Fabrique le nombre vingt-six. Le bouton plus, à gauche, ajoute une grande barre de dix. Le bouton plus, à droite, ajoute un petit cube. Quand tu as fini, touche le bouton vert.",
  c1_10_e: "Vingt-six, c'est deux barres de dix, et six petits cubes.",
  c1_11_c: "Tu as quatre billes. On t'en donne deux. Combien de billes as-tu maintenant ?",
  c1_11_e: "Quatre billes, plus deux billes : ça fait six billes.",
  c1_12_c: "Il faut six cartes. Il y en a déjà deux. Combien en manque-t-il ?",
  c1_12_e: "Deux cartes, plus quatre cartes, ça fait six. Il en manque quatre.",
  c1_13_c: "Touche le nombre le plus grand.",
  c1_13_e: "Quarante-deux a quatre dizaines. Vingt-quatre n'en a que deux. Le plus grand, c'est quarante-deux.",
  c1_14_c: "Tu as sept bonbons. Tu en donnes deux à un ami. Combien de bonbons te reste-t-il ?",
  c1_14_e: "Sept bonbons, moins les deux que tu as donnés : il en reste cinq.",
  c1_15_c: "On veut sept bonbons. On en a déjà cinq. Combien faut-il en ajouter ?",
  c1_15_e: "Cinq, puis six, sept : il faut en ajouter deux. Cinq plus deux égale sept.",

  // --- Parcours C, séance 2 ---
  c2_01_c: "Il en faut dix. Il y en a huit. Combien en manque-t-il ?",
  c2_01_e: "Huit cases sont pleines, et il reste deux cases vides. Huit plus deux égale dix.",
  c2_02_c: "Sept, plus combien, égale dix ?",
  c2_02_e: "Sept cases sont pleines. Il en faut encore trois. Sept plus trois égale dix.",
  c2_03_c: "Il faut huit étoiles. Il y en a déjà cinq. Combien en manque-t-il ?",
  c2_03_e: "Cinq étoiles, plus trois étoiles, ça fait huit. Huit, c'est cinq plus trois.",
  c2_04_c: "Un dé est caché. L'autre dé a trois points. En tout, il y a cinq points. Combien de points sur le dé caché ?",
  c2_04_e: "Deux points, plus trois points, ça fait cinq. Sur le dé caché, il y a deux points.",
  c2_05_c: "Quatre, plus combien, égale dix ?",
  c2_05_e: "Il y a six cases vides. Quatre plus six égale dix.",
  c2_06_c: "On veut neuf billes. On en a déjà cinq. Combien faut-il en ajouter ?",
  c2_06_e: "Cinq, puis six, sept, huit, neuf : il faut en ajouter quatre. Cinq plus quatre égale neuf.",
  c2_07_c: "Combien, plus un, égale trois ? Regarde : un dé est caché, l'autre a un point.",
  c2_07_e: "Deux, plus un, ça fait trois. Le nombre caché, c'est deux.",
  c2_08_c: "Combien font quatre plus cinq ? Pense à quatre plus quatre.",
  c2_08_e: "Quatre plus quatre, ça fait huit. Cinq, c'est un de plus. Quatre plus cinq égale neuf.",
  c2_09_c: "Fabrique le nombre quarante-trois, avec les barres de dix et les petits cubes. Quand tu as fini, touche le bouton vert.",
  c2_09_e: "Quarante-trois, c'est quatre barres de dix, et trois petits cubes.",
  c2_10_c: "Il y a huit cartes. Tom en prend trois. Combien de cartes reste-t-il ?",
  c2_10_e: "Huit cartes, moins les trois que Tom a prises : il en reste cinq.",
  c2_11_c: "On veut huit étoiles. On en a déjà six. Combien faut-il en ajouter ?",
  c2_11_e: "Six, puis sept, huit : il faut en ajouter deux. Six plus deux égale huit.",
  c2_12_c: "Voici quarante-sept. Combien y a-t-il de grandes barres de dix ?",
  c2_12_e: "Quarante-sept, c'est quatre barres de dix, et sept petits cubes. Le premier chiffre, quatre, dit combien il y a de barres.",
  c2_13_c: "Léa a cinq étoiles. Elle en gagne quatre. Combien d'étoiles a-t-elle maintenant ?",
  c2_13_e: "Cinq étoiles, plus quatre étoiles : ça fait neuf étoiles.",
  c2_14_c: "Touche le nombre le plus petit.",
  c2_14_e: "Cinquante-cinq et cinquante-sept ont tous les deux cinq dizaines. Cinquante-cinq a moins de petits cubes : c'est le plus petit.",
  c2_15_c: "Dix, c'est trois plus combien ?",
  c2_15_e: "Il y a sept cases vides. Dix, c'est trois plus sept.",

  // --- Parcours C, séance 3 ---
  c3_01_c: "Cinq, plus combien, égale dix ?",
  c3_01_e: "Cinq plus cinq égale dix. La boîte a deux lignes de cinq.",
  c3_02_c: "Huit, c'est cinq plus combien ? Tu peux t'aider de tes doigts : montre cinq doigts, puis ajoute des doigts jusqu'à huit.",
  c3_02_e: "Cinq, puis six, sept, huit : on a ajouté trois. Huit, c'est cinq plus trois.",
  c3_03_c: "Combien, plus trois, égale cinq ? Le nombre à trouver est au début.",
  c3_03_e: "Deux, plus trois, ça fait cinq. Le nombre qui manque, c'est deux. On n'ajoute pas trois et cinq : cinq, c'est le total.",
  c3_04_c: "Neuf, c'est sept plus combien ?",
  c3_04_e: "Sept, puis huit, neuf : on a ajouté deux. Neuf, c'est sept plus deux.",
  c3_05_c: "Combien, plus deux, égale six ?",
  c3_05_e: "Quatre, plus deux, ça fait six. Le nombre qui manque, c'est quatre.",
  c3_06_c: "Combien font cinq plus quatre ?",
  c3_06_e: "Cinq plus quatre, c'est pareil que quatre plus cinq : on a juste changé l'ordre. Ça fait neuf.",
  c3_07_c: "Léa veut dix étoiles. Elle en a déjà sept. Combien d'étoiles lui manque-t-il ?",
  c3_07_e: "Sept étoiles, plus trois étoiles, ça fait dix. Il lui en manque trois.",
  c3_08_c: "Attention, regarde bien le signe : c'est un moins. Combien font huit moins deux ?",
  c3_08_e: "C'est un moins : on enlève. Huit moins deux, il reste six.",
  c3_09_c: "Sept, c'est trois plus combien ? Tu peux t'aider de tes doigts.",
  c3_09_e: "Trois, puis quatre, cinq, six, sept : on a ajouté quatre. Sept, c'est trois plus quatre.",
  c3_10_c: "Touche le nombre le plus grand.",
  c3_10_e: "Quatre-vingt-seize a neuf dizaines. Soixante-neuf n'en a que six. Le plus grand, c'est quatre-vingt-seize.",
  c3_11_c: "Tu as dix billes. Tu en perds quatre. Combien de billes te reste-t-il ?",
  c3_11_e: "Dix billes, moins les quatre perdues : il en reste six.",
  c3_12_c: "Combien font quatre plus six ?",
  c3_12_e: "Quatre plus six égale dix. C'est comme six plus quatre : la boîte est pleine.",
  c3_13_c: "Voici cinquante-huit. Combien y a-t-il de petits cubes, à côté des barres ?",
  c3_13_e: "Cinquante-huit, c'est cinq barres de dix, et huit petits cubes. Le deuxième chiffre, huit, dit combien il y a de petits cubes.",
  c3_14_c: "Tom a cinq cartes. Léa a deux cartes de plus que Tom. Combien de cartes a Léa ?",
  c3_14_e: "Léa a autant de cartes que Tom, et encore deux. Cinq plus deux, ça fait sept cartes.",
  c3_15_c: "Dix, c'est six plus combien ?",
  c3_15_e: "Six, puis sept, huit, neuf, dix : on a ajouté quatre. Dix, c'est six plus quatre.",

  // --- Parcours N, séance 1 ---
  n1_01_c: "Écoute : quatre-vingt-sept, quatre-vingt-huit, quatre-vingt-neuf… Quel nombre vient juste après ?",
  n1_01_e: "Après quatre-vingt-neuf, il y a quatre-vingt-dix : neuf barres de dix.",
  n1_02_c: "Quel nombre vient juste après quatre-vingt-quatorze ?",
  n1_02_e: "Après quatre-vingt-quatorze, il y a quatre-vingt-quinze.",
  n1_03_c: "Attention, écoute bien. Quel nombre vient juste avant quatre-vingt-dix ?",
  n1_03_e: "Juste avant quatre-vingt-dix, il y a quatre-vingt-neuf. Avant, c'est un de moins.",
  n1_04_c: "Combien y a-t-il de cubes en tout ?",
  n1_04_e: "Neuf barres de dix, ça fait quatre-vingt-dix. Plus trois petits cubes : quatre-vingt-treize.",
  n1_05_c: "Écoute bien le nombre, puis tape-le : quatre-vingt-dix-sept.",
  n1_05_e: "Quatre-vingt-dix-sept, c'est neuf barres de dix, et sept petits cubes. On écrit le chiffre neuf, puis le chiffre sept.",
  n1_06_c: "Fabrique le nombre soixante-seize, avec les barres de dix et les petits cubes. Quand tu as fini, touche le bouton vert.",
  n1_06_e: "Soixante-seize, c'est sept barres de dix, et six petits cubes : soixante-dix, et encore six.",
  n1_07_c: "Tom a six billes. Léa a quatre billes de plus que Tom. Combien de billes a Léa ?",
  n1_07_e: "Léa a autant de billes que Tom, et encore quatre. Six plus quatre, ça fait dix billes.",
  n1_08_c: "Combien font quarante plus trente ?",
  n1_08_e: "Quatre barres de dix, plus trois barres de dix : sept barres. Quarante plus trente égale soixante-dix.",
  n1_09_c: "Un ami a calculé huit plus cinq, et il a trouvé douze. Vérifie. Quel est le bon résultat ?",
  n1_09_e: "Huit, plus deux pour faire dix, plus encore trois : treize. Huit plus cinq égale treize.",
  n1_10_c: "Touche le nombre le plus grand.",
  n1_10_e: "Quatre-vingt-dix-sept a neuf dizaines. C'est le plus grand.",
  n1_11_c: "Léa a neuf cartes. Tom a trois cartes de moins que Léa. Combien de cartes a Tom ?",
  n1_11_e: "Tom en a moins que Léa : on enlève trois. Neuf moins trois, ça fait six cartes.",
  n1_12_c: "Voici une ligne qui va de zéro à cent. Touche l'endroit où se trouve quatre-vingt-dix.",
  n1_12_e: "Quatre-vingt-dix est tout près de cent : il ne manque que dix.",
  n1_13_c: "Regarde les barres. Quarante-sept, plus une barre de dix. Combien font quarante-sept plus dix ?",
  n1_13_e: "Plus dix, on ajoute une barre de dix : quarante-sept, cinquante-sept. Quarante-sept plus dix égale cinquante-sept.",
  n1_14_c: "Écoute : quatre-vingt-quinze, quatre-vingt-dix, quatre-vingt-cinq… Quel nombre vient après ?",
  n1_14_e: "On recule de cinq en cinq : quatre-vingt-quinze, quatre-vingt-dix, quatre-vingt-cinq, quatre-vingts.",
  n1_15_c: "Il y a douze bonbons. On en mange cinq. Combien de bonbons reste-t-il ?",
  n1_15_e: "Douze bonbons, moins les cinq mangés : il en reste sept.",

  // --- Parcours N, séance 2 ---
  n2_01_c: "Quel nombre vient juste après quatre-vingt-dix-neuf ?",
  n2_01_e: "Après quatre-vingt-dix-neuf, il y a cent. Cent, c'est dix barres de dix. On l'écrit avec trois chiffres : un, zéro, zéro.",
  n2_02_c: "Écoute bien le nombre, puis tape-le : soixante-quatorze.",
  n2_02_e: "Soixante-quatorze, c'est sept barres de dix, et quatre petits cubes. On écrit le chiffre sept, puis le chiffre quatre.",
  n2_03_c: "Attention, regarde bien les petits cubes. Combien y a-t-il de cubes en tout ?",
  n2_03_e: "Trois barres, ça fait trente. Douze petits cubes, c'est encore une barre de dix et deux cubes. Trente plus douze égale quarante-deux.",
  n2_04_c: "Fabrique le nombre soixante, avec les barres de dix et les petits cubes. Quand tu as fini, touche le bouton vert.",
  n2_04_e: "Soixante, c'est six barres de dix, et aucun petit cube.",
  n2_05_c: "Combien font neuf plus six ?",
  n2_05_e: "Neuf, plus un pour faire dix, plus encore cinq : quinze. Neuf plus six égale quinze.",
  n2_06_c: "Tom a quinze billes. Léa a cinq billes de plus que Tom. Combien de billes a Léa ?",
  n2_06_e: "Léa a autant de billes que Tom, et encore cinq. Quinze plus cinq, ça fait vingt billes.",
  n2_07_c: "Regarde les barres. Trente, c'est trois barres de dix. Vingt, c'est deux barres de dix. Combien font trente plus vingt ? Compte les barres de dix en dix.",
  n2_07_e: "Trois barres, plus deux barres, ça fait cinq barres. Dix, vingt, trente, quarante, cinquante. Trente plus vingt égale cinquante.",
  n2_08_c: "Soixante-quatre, c'est soixante plus combien ?",
  n2_08_e: "Soixante-quatre, c'est six barres de dix, et quatre petits cubes. Soixante-quatre, c'est soixante plus quatre.",
  n2_09_c: "Un ami a calculé quarante plus cinq, et il a trouvé quatre-vingt-dix. Vérifie. Quel est le bon résultat ?",
  n2_09_e: "Quarante, ce sont quatre barres. Cinq, ce sont cinq petits cubes, pas des barres. Quarante plus cinq égale quarante-cinq.",
  n2_10_c: "Tu as cinq billes. On t'en donne quatre. Puis tu en perds deux. Combien de billes as-tu maintenant ?",
  n2_10_e: "Cinq plus quatre, ça fait neuf. Puis neuf moins deux, ça fait sept billes.",
  n2_11_c: "Touche le nombre le plus petit.",
  n2_11_e: "Soixante-six et soixante-huit ont six dizaines. Soixante-six a moins de petits cubes : c'est le plus petit.",
  n2_12_c: "Voici une ligne qui va de zéro à cent. Touche l'endroit où se trouve vingt-cinq.",
  n2_12_e: "Vingt-cinq est au milieu, entre zéro et cinquante.",
  n2_13_c: "Léa a vingt cartes. Tom a quatre cartes de moins que Léa. Combien de cartes a Tom ?",
  n2_13_e: "Tom en a moins que Léa : on enlève quatre. Vingt moins quatre, ça fait seize cartes.",
  n2_14_c: "Écoute : trois, six, neuf… Quel nombre vient après ?",
  n2_14_e: "On avance de trois en trois : trois, six, neuf, douze.",
  n2_15_c: "Une boîte peut contenir vingt cartes. Il y a déjà dix-sept cartes dedans. Combien de cartes peut-on encore mettre ?",
  n2_15_e: "Dix-sept, puis dix-huit, dix-neuf, vingt : on peut encore en mettre trois. Dix-sept plus trois égale vingt.",

  // --- Parcours N, séance 3 ---
  n3_01_c: "Quel nombre vient juste après soixante-dix-neuf ?",
  n3_01_e: "Après soixante-dix-neuf, il y a quatre-vingts : huit barres de dix.",
  n3_02_c: "Écoute bien le nombre, puis tape-le : quatre-vingt-onze.",
  n3_02_e: "Quatre-vingt-onze, c'est neuf barres de dix, et un petit cube. On écrit le chiffre neuf, puis le chiffre un.",
  n3_03_c: "Cinquante-deux, c'est combien plus deux ?",
  n3_03_e: "Cinquante-deux, c'est cinq barres de dix, et deux petits cubes. Cinquante-deux, c'est cinquante plus deux.",
  n3_04_c: "Regarde les barres. Combien font trente-six plus vingt ?",
  n3_04_e: "Plus vingt, on ajoute deux barres de dix : trente-six, quarante-six, cinquante-six. Trente-six plus vingt égale cinquante-six.",
  n3_05_c: "Tom a sept billes. Léa a dix billes. Combien de billes Léa a-t-elle de plus que Tom ?",
  n3_05_e: "Pour aller de sept à dix : huit, neuf, dix. Léa a trois billes de plus que Tom.",
  n3_06_c: "Fabrique le nombre quatre-vingt-cinq, avec les barres de dix et les petits cubes. Quand tu as fini, touche le bouton vert.",
  n3_06_e: "Quatre-vingt-cinq, c'est huit barres de dix, et cinq petits cubes.",
  n3_07_c: "Un ami a calculé cinquante plus vingt, et il a trouvé cinquante-deux. Vérifie. Quel est le bon résultat ?",
  n3_07_e: "Vingt, ce sont deux barres de dix, pas deux petits cubes. Cinq barres plus deux barres, ça fait sept barres : soixante-dix.",
  n3_08_c: "Combien font quinze moins six ?",
  n3_08_e: "Quinze moins cinq, ça fait dix. Moins encore un, ça fait neuf. Quinze moins six égale neuf.",
  n3_09_c: "Léa a douze cartes. Elle a quatre cartes de plus que Tom. Combien de cartes a Tom ?",
  n3_09_e: "C'est Léa qui en a le plus. Tom en a donc quatre de moins : douze moins quatre, ça fait huit cartes.",
  n3_10_c: "Touche le nombre le plus grand.",
  n3_10_e: "Cent vient juste après quatre-vingt-dix-neuf. Cent est le plus grand.",
  n3_11_c: "Écoute bien : cent… quatre-vingt-dix… quatre-vingts… Quel nombre vient après ?",
  n3_11_e: "On recule de dix en dix : cent, quatre-vingt-dix, quatre-vingts, soixante-dix.",
  n3_12_c: "Voici une ligne, de zéro à cent. Touche l'endroit où se trouve soixante-quinze.",
  n3_12_e: "Soixante-quinze est entre cinquante et cent, juste au milieu.",
  n3_13_c: "Dans un sac, il y a dix billes. On en ajoute quatre. Puis on en retire trois. Combien de billes y a-t-il dans le sac ?",
  n3_13_e: "Dix plus quatre, ça fait quatorze. Puis quatorze moins trois, ça fait onze billes.",
  n3_14_c: "Dans quatre-vingt-sept, combien y a-t-il de dizaines ?",
  n3_14_e: "Quatre-vingt-sept, c'est huit barres de dix, et sept petits cubes. Il y a huit dizaines.",
  n3_15_c: "Il faut cinquante points pour gagner. Tom a déjà quarante-six points. Combien de points lui manque-t-il ?",
  n3_15_e: "Quarante-six, puis quarante-sept, quarante-huit, quarante-neuf, cinquante : il lui manque quatre points.",

  // --- Parcours C, séance 4 ---
  c4_01_c: "Regarde le dé. Combien y a-t-il de points ?",
  c4_01_e: "Il y a quatre points : un dans chaque coin du dé.",
  c4_02_c: "Il faut cinq points en tout, sur les deux dés. Combien de points faut-il sur le dé caché ?",
  c4_02_e: "Trois points, plus deux points, ça fait cinq. Il faut deux points.",
  c4_03_c: "Il faut cinq points en tout. Combien de points faut-il sur le dé caché ?",
  c4_03_e: "Un point, plus quatre points, ça fait cinq. Il faut quatre points.",
  c4_04_c: "Les deux dés sont pareils. Combien de points y a-t-il en tout ?",
  c4_04_e: "Deux plus deux, ça fait quatre. C'est le double de deux.",
  c4_05_c: "Il faut cinq points en tout. Combien de points faut-il sur le dé caché ?",
  c4_05_e: "Quatre points, plus un point, ça fait cinq. Il faut un point.",
  c4_06_c: "Les deux dés sont pareils. Combien de points y a-t-il en tout ?",
  c4_06_e: "Trois plus trois, ça fait six. C'est le double de trois.",
  c4_07_c: "Sur cette ligne, on avance de un en un. Quel nombre est sous la flèche orange ?",
  c4_07_e: "On part de cinq, et on avance : six, sept. La flèche montre sept.",
  c4_08_c: "Il faut cinq points en tout. Combien de points faut-il sur le dé caché ?",
  c4_08_e: "Deux points, plus trois points, ça fait cinq. Il faut trois points.",
  c4_09_c: "Combien y a-t-il de points en tout, sur les deux dés ?",
  c4_09_e: "Cinq, puis six, sept, huit. Cinq plus trois, ça fait huit. Huit, c'est cinq plus trois.",
  c4_10_c: "Les deux dés sont pareils. Combien de points y a-t-il en tout ?",
  c4_10_e: "Cinq plus cinq, ça fait dix. C'est le double de cinq.",
  c4_11_c: "Combien y a-t-il de cubes en tout ? Compte d'abord les barres de dix.",
  c4_11_e: "Dix, vingt, trente, quarante : quatre barres. Plus six petits cubes : quarante-six.",
  c4_12_c: "Cinq, c'est deux plus combien ?",
  c4_12_e: "Deux, puis trois, quatre, cinq : on a ajouté trois. Cinq, c'est deux plus trois.",
  c4_13_c: "Les deux dés sont pareils. Combien de points y a-t-il en tout ?",
  c4_13_e: "Quatre plus quatre, ça fait huit. C'est le double de quatre.",
  c4_14_c: "Léa a cinq bonbons. Elle en mange. Maintenant, il lui en reste deux. Combien de bonbons a-t-elle mangés ?",
  c4_14_e: "Elle avait cinq bonbons. Il en reste deux. Elle en a mangé trois, car deux plus trois, ça fait cinq.",
  c4_15_c: "Six, plus combien, égale dix ?",
  c4_15_e: "Il y a quatre cases vides. Six plus quatre égale dix.",

  // --- Parcours C, séance 5 ---
  c5_01_c: "Il faut cinq points en tout. Combien de points faut-il sur le dé caché ?",
  c5_01_e: "Un point, plus quatre points, ça fait cinq. Il faut quatre points.",
  c5_02_c: "Combien font trois plus trois ?",
  c5_02_e: "Trois plus trois, ça fait six. C'est le double de trois, comme deux dés de trois points.",
  c5_03_c: "Sept, c'est cinq plus combien ? Regarde le dé de cinq.",
  c5_03_e: "Cinq, puis six, sept : on a ajouté deux. Sept, c'est cinq plus deux.",
  c5_04_c: "Sur cette ligne, on avance de un en un. Quel nombre est sous la flèche orange ?",
  c5_04_e: "On part de dix, et on avance : onze, douze, treize. La flèche montre treize.",
  c5_05_c: "Combien font quatre plus quatre ?",
  c5_05_e: "Quatre plus quatre, ça fait huit. C'est le double de quatre.",
  c5_06_c: "Neuf, c'est cinq plus combien ? Regarde le dé de cinq.",
  c5_06_e: "Cinq, puis six, sept, huit, neuf : on a ajouté quatre. Neuf, c'est cinq plus quatre.",
  c5_07_c: "Dix, c'est huit plus combien ?",
  c5_07_e: "Huit, puis neuf, dix : on a ajouté deux. Dix, c'est huit plus deux.",
  c5_08_c: "Écoute bien le nombre, puis tape-le : quatre-vingt-douze.",
  c5_08_e: "Quatre-vingt-douze, c'est neuf barres de dix, et deux petits cubes. On écrit le chiffre neuf, puis le chiffre deux.",
  c5_09_c: "Voici soixante-trois. Combien y a-t-il de grandes barres de dix ?",
  c5_09_e: "Soixante-trois, c'est six barres de dix, et trois petits cubes. Le premier chiffre, six, dit combien il y a de barres.",
  c5_10_c: "Combien font cinq plus cinq ?",
  c5_10_e: "Cinq plus cinq, ça fait dix. C'est le double de cinq : deux mains.",
  c5_11_c: "Tom avait six cartes. On lui en donne. Maintenant, il en a huit. Combien de cartes lui a-t-on données ?",
  c5_11_e: "Six, puis sept, huit : on lui a donné deux cartes. Six plus deux, ça fait huit.",
  c5_12_c: "Cinq, c'est quatre plus combien ?",
  c5_12_e: "Quatre, puis cinq : on a ajouté un. Cinq, c'est quatre plus un.",
  c5_13_c: "Combien font douze plus treize ?",
  c5_13_e: "Une barre de dix plus une barre de dix, ça fait vingt. Deux cubes plus trois cubes, ça fait cinq. Douze plus treize égale vingt-cinq.",
  c5_14_c: "On partage ces six bonbons entre deux amis. Chacun en a autant. Combien de bonbons pour chaque ami ?",
  c5_14_e: "Trois bonbons pour l'un, trois bonbons pour l'autre. Trois plus trois, ça fait six. Chacun en a trois.",
  c5_15_c: "Fabrique le nombre cinquante-neuf, avec les barres de dix et les petits cubes. Quand tu as fini, touche le bouton vert.",
  c5_15_e: "Cinquante-neuf, c'est cinq barres de dix, et neuf petits cubes.",

  // --- Parcours N, séance 4 ---
  n4_01_c: "Les deux dés sont pareils. Combien de points y a-t-il en tout ?",
  n4_01_e: "Quatre plus quatre, ça fait huit. C'est le double de quatre.",
  n4_02_c: "Il faut cinq points en tout, sur les deux dés. Combien de points faut-il sur le dé caché ?",
  n4_02_e: "Deux points, plus trois points, ça fait cinq. Il faut trois points.",
  n4_03_c: "Combien font six plus six ?",
  n4_03_e: "Six plus six, ça fait douze. C'est le double de six.",
  n4_04_c: "On partage ces dix billes en deux parts égales. Combien de billes dans chaque part ?",
  n4_04_e: "Cinq billes et cinq billes, ça fait dix. Chaque part a cinq billes : c'est la moitié de dix.",
  n4_05_c: "Sur cette ligne, on avance de un en un. Quel nombre est sous la flèche orange ?",
  n4_05_e: "Entre quarante et cinquante, le milieu est quarante-cinq. Puis quarante-six, quarante-sept. La flèche montre quarante-sept.",
  n4_06_c: "Regarde les barres. Combien font vingt-trois plus quatorze ? Compte d'abord les barres, puis les petits cubes.",
  n4_06_e: "Vingt plus dix, ça fait trente. Trois plus quatre, ça fait sept. Vingt-trois plus quatorze égale trente-sept.",
  n4_07_c: "Léa avait des cartes. Elle en gagne trois. Maintenant, elle en a neuf. Combien de cartes avait-elle avant ?",
  n4_07_e: "Elle en a neuf maintenant, dont trois gagnées. Avant, elle en avait neuf moins trois : six cartes.",
  n4_08_c: "Combien font vingt plus vingt ?",
  n4_08_e: "Deux barres de dix, plus deux barres de dix : quatre barres. Vingt plus vingt égale quarante. C'est le double de vingt.",
  n4_09_c: "Un ami a calculé six plus six, et il a trouvé treize. Vérifie. Quel est le bon résultat ?",
  n4_09_e: "Six plus six, c'est le double de six : douze. Treize, c'est un de trop.",
  n4_10_c: "Regarde bien les barres. Combien font trente-quatre plus dix ?",
  n4_10_e: "Plus dix, on ajoute une barre de dix : trente-quatre, quarante-quatre. Trente-quatre plus dix égale quarante-quatre.",
  n4_11_c: "Soixante-trois, plus combien, égale soixante-dix ?",
  n4_11_e: "Soixante-trois, puis soixante-quatre, et ainsi de suite jusqu'à soixante-dix : on a ajouté sept. Soixante-trois plus sept égale soixante-dix.",
  n4_12_c: "Tom a douze billes. Léa a huit billes. Combien de billes Tom a-t-il de plus que Léa ?",
  n4_12_e: "Pour aller de huit à douze : neuf, dix, onze, douze. Tom a quatre billes de plus que Léa.",
  n4_13_c: "Combien font quarante moins trois ?",
  n4_13_e: "Quarante moins un, trente-neuf. Moins deux, trente-huit. Moins trois, trente-sept.",
  n4_14_c: "Regarde les barres. Combien font trente-deux plus vingt-cinq ? Compte d'abord les barres, puis les petits cubes.",
  n4_14_e: "Trente plus vingt, ça fait cinquante. Deux plus cinq, ça fait sept. Trente-deux plus vingt-cinq égale cinquante-sept.",
  n4_15_c: "Quarante, c'est deux nombres pareils. Quelle est la moitié de quarante ?",
  n4_15_e: "Vingt plus vingt, ça fait quarante. La moitié de quarante, c'est vingt.",

  // --- Parcours N, séance 5 ---
  n5_01_c: "Il faut cinq points en tout, sur les deux dés. Combien de points faut-il sur le dé caché ?",
  n5_01_e: "Trois points, plus deux points, ça fait cinq. Il faut deux points.",
  n5_02_c: "Combien font sept plus sept ?",
  n5_02_e: "Sept plus sept, ça fait quatorze. C'est le double de sept.",
  n5_03_c: "Combien font sept plus huit ? Pense au double de sept.",
  n5_03_e: "Sept plus sept, ça fait quatorze. Huit, c'est un de plus que sept. Donc sept plus huit, ça fait quinze.",
  n5_04_c: "Sur cette ligne, on avance de un en un. Quel nombre est sous la flèche orange ?",
  n5_04_e: "On part de quatre-vingts, et on avance : quatre-vingt-un, quatre-vingt-deux, quatre-vingt-trois. La flèche montre quatre-vingt-trois.",
  n5_05_c: "Combien font cinquante plus trente ? Pense aux barres de dix.",
  n5_05_e: "Cinq barres de dix, plus trois barres de dix, ça fait huit barres. Cinquante plus trente égale quatre-vingts.",
  n5_06_c: "Dans une boîte, il y avait des billes. On en enlève quatre. Il en reste sept. Combien de billes y avait-il au début ?",
  n5_06_e: "Il en reste sept, et on en a enlevé quatre. Au début, il y en avait sept plus quatre : onze billes.",
  n5_07_c: "Seize, c'est deux nombres pareils. Quelle est la moitié de seize ?",
  n5_07_e: "Huit plus huit, ça fait seize. La moitié de seize, c'est huit.",
  n5_08_c: "Un ami a calculé quarante-cinq plus vingt, et il a trouvé quarante-sept. Vérifie. Quel est le bon résultat ?",
  n5_08_e: "Vingt, ce sont deux barres de dix, pas deux petits cubes. Quarante-cinq plus vingt égale soixante-cinq.",
  n5_09_c: "Combien font cinquante plus cinquante ?",
  n5_09_e: "Cinq barres de dix, plus cinq barres de dix : dix barres. Cinquante plus cinquante égale cent.",
  n5_10_c: "Combien font cinquante-six plus dix ?",
  n5_10_e: "Plus dix, on ajoute une barre de dix : cinquante-six, soixante-six. Cinquante-six plus dix égale soixante-six.",
  n5_11_c: "Combien font soixante moins quatre ?",
  n5_11_e: "Soixante moins un, cinquante-neuf. Puis cinquante-huit, cinquante-sept, cinquante-six. Soixante moins quatre égale cinquante-six.",
  n5_12_c: "Tom a huit billes. Il en gagne sept. Puis il en donne cinq. Combien de billes a-t-il maintenant ?",
  n5_12_e: "Huit plus sept, ça fait quinze. Puis quinze moins cinq, ça fait dix billes.",
  n5_13_c: "Dans cinquante-huit, le chiffre cinq vaut combien ?",
  n5_13_e: "Le cinq est le chiffre des dizaines : cinq barres de dix. Il vaut cinquante. Cinquante-huit, c'est cinquante plus huit.",
  n5_14_c: "Il y a trois boîtes. Dans chaque boîte, il y a quatre bonbons. Combien de bonbons y a-t-il en tout ?",
  n5_14_e: "Quatre, plus quatre, plus quatre : huit, puis douze. Il y a douze bonbons.",
  n5_15_c: "Combien font quarante-quatre plus trente-cinq ?",
  n5_15_e: "Quarante plus trente, ça fait soixante-dix. Quatre plus cinq, ça fait neuf. Quarante-quatre plus trente-cinq égale soixante-dix-neuf.",

  // --- Séances S1.4 (parcours N, séances 6 à 8) — textes figés : la voix est générée à partir d'eux ---
  n6_01_c: "Écris le nombre soixante-douze.",
  n6_01_e: "Soixante-douze, c'est sept dizaines et deux unités. On écrit sept, puis deux.",
  n6_02_c: "Écris le nombre quatre-vingt-un.",
  n6_02_e: "Quatre-vingt-un, c'est huit dizaines et une unité. On écrit huit, puis un.",
  n6_03_c: "Écris le nombre quatre-vingt-douze.",
  n6_03_e: "Quatre-vingt-douze, c'est neuf dizaines et deux unités. On écrit neuf, puis deux. Seulement deux chiffres.",
  n6_04_c: "Écris le nombre soixante-dix-huit.",
  n6_04_e: "Soixante-dix-huit, c'est sept dizaines et huit unités. On écrit sept, puis huit.",
  n6_05_c: "Écris le nombre quatre-vingt-dix-sept.",
  n6_05_e: "Quatre-vingt-dix-sept, c'est neuf dizaines et sept unités. On écrit neuf, puis sept.",
  n6_06_c: "Écris le nombre quatre-vingt-cinq.",
  n6_06_e: "Quatre-vingt-cinq, c'est huit dizaines et cinq unités. On écrit huit, puis cinq.",
  n6_07_c: "Écris le nombre soixante et onze.",
  n6_07_e: "Soixante et onze, c'est sept dizaines et une unité. On écrit sept, puis un.",
  n6_08_c: "Écris le nombre quatre-vingt-dix-neuf.",
  n6_08_e: "Quatre-vingt-dix-neuf, c'est neuf dizaines et neuf unités. On écrit neuf, puis neuf.",
  n6_09_c: "Il y a une dizaine et quatre unités. Écris ce nombre.",
  n6_09_e: "Une dizaine et quatre unités, ça fait quatorze. On écrit d'abord les dizaines : un, puis quatre.",
  n6_10_c: "Il y a trois dizaines et cinq unités. Écris ce nombre.",
  n6_10_e: "Trois dizaines et cinq unités, ça fait trente-cinq. D'abord les dizaines : trois, puis cinq.",
  n6_11_c: "Il y a cinq dizaines et trois unités. Écris ce nombre.",
  n6_11_e: "Cinq dizaines et trois unités, ça fait cinquante-trois. D'abord les dizaines : cinq, puis trois.",
  n6_12_c: "Dix plus quatre, combien ça fait ?",
  n6_12_e: "Dix plus quatre, ça fait quatorze : une dizaine et quatre unités. On écrit un, puis quatre.",
  n6_13_c: "Quatre plus vingt, combien ça fait ?",
  n6_13_e: "Quatre plus vingt, ça fait vingt-quatre : deux dizaines et quatre unités. On écrit deux, puis quatre.",
  n6_14_c: "Il y a huit dizaines et deux unités. Écris ce nombre.",
  n6_14_e: "Huit dizaines et deux unités, ça fait quatre-vingt-deux. On écrit huit, puis deux.",
  n6_15_c: "Il y a neuf dizaines et une unité. Écris ce nombre.",
  n6_15_e: "Neuf dizaines et une unité, ça fait quatre-vingt-onze. On écrit neuf, puis un.",
  n7_01_c: "Trente plus vingt, combien ça fait ?",
  n7_01_e: "Trois dizaines plus deux dizaines, ça fait cinq dizaines : cinquante.",
  n7_02_c: "Quarante plus trente, combien ça fait ?",
  n7_02_e: "Quatre dizaines plus trois dizaines, ça fait sept dizaines : soixante-dix.",
  n7_03_c: "Cinquante plus quarante, combien ça fait ?",
  n7_03_e: "Cinq dizaines plus quatre dizaines, ça fait neuf dizaines : quatre-vingt-dix.",
  n7_04_c: "Vingt plus soixante, combien ça fait ?",
  n7_04_e: "Deux dizaines plus six dizaines, ça fait huit dizaines : quatre-vingts.",
  n7_05_c: "Dix plus cinquante, combien ça fait ?",
  n7_05_e: "Une dizaine plus cinq dizaines, ça fait six dizaines : soixante.",
  n7_06_c: "Quarante plus trois, combien ça fait ?",
  n7_06_e: "Quarante plus trois, c'est quatre dizaines et trois unités : quarante-trois.",
  n7_07_c: "Trois plus cinquante, combien ça fait ?",
  n7_07_e: "Trois plus cinquante, c'est cinq dizaines et trois unités : cinquante-trois. Les dizaines s'écrivent en premier.",
  n7_08_c: "Soixante plus sept, combien ça fait ?",
  n7_08_e: "Soixante plus sept, c'est six dizaines et sept unités : soixante-sept.",
  n7_09_c: "Cinquante, soixante, soixante-dix. Quel nombre vient après ?",
  n7_09_e: "On ajoute une dizaine à chaque fois. Après soixante-dix, il y a quatre-vingts.",
  n7_10_c: "Cinq, dix, quinze. Quel nombre vient après ?",
  n7_10_e: "On ajoute cinq à chaque fois. Après quinze, il y a vingt.",
  n7_11_c: "Vingt, vingt-cinq, trente. Quel nombre vient après ?",
  n7_11_e: "On ajoute cinq à chaque fois. Après trente, il y a trente-cinq.",
  n7_12_c: "Vingt, puis quinze, puis dix. On compte à l'envers. Quel nombre vient après ?",
  n7_12_e: "On enlève cinq à chaque fois. Après dix, il y a cinq.",
  n7_13_c: "Trente, vingt-cinq, vingt. On compte à l'envers. Quel nombre vient après ?",
  n7_13_e: "On enlève cinq à chaque fois. Après vingt, il y a quinze.",
  n7_14_c: "Tom a six billes. Léa a trois billes de plus que Tom. Combien de billes a Léa ?",
  n7_14_e: "Léa a autant de billes que Tom, et trois de plus. Six plus trois, c'est une main et quatre doigts : neuf.",
  n7_15_c: "Léa a sept billes. Tom a cinq billes de plus que Léa. Combien de billes a Tom ?",
  n7_15_e: "Tom a autant de billes que Léa, et cinq de plus. Sept plus cinq, c'est cinq plus cinq, plus deux. Dix plus deux : douze.",
  n8_01_c: "Cinq, c'est trois plus combien ?",
  n8_01_e: "Cinq, c'est trois et deux. Trois plus deux, ça fait cinq.",
  n8_02_c: "Cinq, c'est un plus combien ?",
  n8_02_e: "Cinq, c'est un et quatre. Un plus quatre, ça fait cinq.",
  n8_03_c: "Cinq plus deux, combien ça fait ?",
  n8_03_e: "Cinq, c'est une main. Une main et deux doigts : sept.",
  n8_04_c: "Cinq plus trois, combien ça fait ?",
  n8_04_e: "Cinq, c'est une main. Une main, et trois doigts : ça fait huit.",
  n8_05_c: "Cinq plus quatre, combien ça fait ?",
  n8_05_e: "Cinq, c'est une main. Une main et quatre doigts : neuf.",
  n8_06_c: "Huit, c'est cinq plus combien ?",
  n8_06_e: "Huit, c'est une main et trois doigts. Huit, c'est cinq plus trois.",
  n8_07_c: "Sept, c'est cinq plus combien ?",
  n8_07_e: "Sept, c'est une main et deux doigts. Sept, c'est cinq plus deux.",
  n8_08_c: "Six, c'est cinq plus combien ?",
  n8_08_e: "Six, c'est une main et un doigt. Six, c'est cinq plus un.",
  n8_09_c: "Trois plus trois, combien ça fait ?",
  n8_09_e: "C'est un double. Trois plus trois, ça fait six.",
  n8_10_c: "Trois plus trois, ça fait six. Alors, trois plus quatre, combien ça fait ?",
  n8_10_e: "Trois plus quatre, c'est trois plus trois, plus un. Six plus un : sept.",
  n8_11_c: "Quatre plus quatre, combien ça fait ?",
  n8_11_e: "C'est un double. Quatre plus quatre, ça fait huit.",
  n8_12_c: "Quatre plus quatre, ça fait huit. Alors, quatre plus cinq, combien ça fait ?",
  n8_12_e: "Quatre plus cinq, c'est quatre plus quatre, plus un. Huit plus un : neuf.",
  n8_13_c: "Deux plus trois, combien ça fait ?",
  n8_13_e: "Deux plus trois, c'est deux plus deux, plus un. Quatre plus un : cinq.",
  n8_14_c: "Quatre plus trois, combien ça fait ?",
  n8_14_e: "Quatre plus trois, c'est trois plus trois, plus un. Six plus un : sept.",
  n8_15_c: "Cinq plus six, combien ça fait ?",
  n8_15_e: "Cinq plus six, c'est cinq plus cinq, plus un. Dix plus un : onze."

};
