// Toutes les phrases dites par l'appli. Identifiant -> texte.
// Les MP3 sont générés à partir de ce fichier (outils/generer_audio.py).
// Les nombres sont écrits en LETTRES pour que la voix les lise correctement.
// Toute modification d'un texte impose de régénérer l'audio.
export const PHRASES = {
  // --- Accueil ---
  qui_joue: "Qui joue aujourd'hui ? Touche ton image.",
  bonjour_koala: "Bonjour petit koala !",
  bonjour_panda: "Bonjour petit panda !",
  bonjour_licorne: "Bonjour petite licorne !",
  bonjour_chiot: "Bonjour petit chiot !",
  accueil_test: "Aujourd'hui, on fait le grand jeu de départ. Touche le bouton vert pour commencer.",
  accueil_reprise: "Ton jeu t'attend. Touche le bouton vert pour continuer.",
  accueil_fini: "Tu as fini le grand jeu de départ. Bravo ! Les prochains jeux arrivent bientôt.",

  // --- Test : cadre ---
  test_intro: "On va faire un petit jeu, pour voir tout ce que tu sais déjà. Écoute bien chaque question. Prends ton temps : ce n'est pas une course. Si tu veux réécouter, touche l'oreille.",
  test_reprise: "On reprend là où on s'était arrêtés.",
  test_pause: "On fait une pause. À tout à l'heure !",
  test_fin: "Bravo, le jeu est fini ! Tu as très bien travaillé. Tu peux aller le dire à un grand.",

  // --- Retours (règle B5 : neutres sur l'erreur, valorisants sur la démarche) ---
  verifie: "Hum… vérifie bien. Regarde encore, et essaie une autre fois.",
  bravo_1: "Bravo !",
  bravo_2: "Très bien !",
  bravo_3: "Oui, c'est ça !",
  bravo_verifie: "Bravo, tu as vérifié, et tu as trouvé !",
  aide_intro: "Ce n'est pas grave. Regarde, je t'explique.",
  suivant: "Touche la flèche pour continuer.",

  // --- Items du test de positionnement (T1) ---
  i01_c: "Regarde bien. Combien y en a-t-il ? Tape le nombre, puis touche le bouton vert.",
  i01_e: "Il y en a cinq, comme sur un dé.",
  i02_c: "Compte bien. Combien y en a-t-il en tout ?",
  i02_e: "Il y en a quatorze. Pour bien compter, on touche chaque image une seule fois.",
  i03_c: "Quel nombre vient juste après trente-neuf ?",
  i03_e: "Après trente-neuf, il y a quarante.",
  i04_c: "Quel nombre vient juste après quatre-vingt-neuf ?",
  i04_e: "Après quatre-vingt-neuf, il y a quatre-vingt-dix.",
  i05_c: "Chaque grande barre a dix cubes. Combien y a-t-il de cubes en tout ?",
  i05_e: "Quatre barres de dix, ça fait quarante. Plus sept petits cubes : quarante-sept.",
  i06_c: "Montre le nombre cinquante-trois, avec des barres de dix et des petits cubes. Puis touche le bouton vert.",
  i06_e: "Cinquante-trois, c'est cinq barres de dix, et trois petits cubes.",
  i07_c: "Touche le nombre le plus grand.",
  i07_e: "Le plus grand, c'est quatre-vingt-trois : il a huit dizaines. Trente-huit n'en a que trois.",
  i08_c: "Voici une ligne qui va de zéro à cent. Touche l'endroit où se trouve cinquante.",
  i08_e: "Cinquante est juste au milieu, entre zéro et cent.",
  i09_c: "Six, plus combien, égale dix ?",
  i09_e: "Six plus quatre égale dix. Regarde : il manque quatre cases pour remplir la boîte.",
  i10_c: "Huit, c'est cinq plus combien ?",
  i10_e: "Huit, c'est cinq plus trois.",
  i11_c: "Combien font six plus trois ?",
  i11_e: "Six plus trois égale neuf.",
  i12_c: "Tu as cinq billes. On t'en donne trois de plus. Combien de billes as-tu maintenant ?",
  i12_e: "Cinq billes, plus trois billes : ça fait huit billes.",
  i13_c: "Tu as neuf bonbons. Tu en manges trois. Combien de bonbons te reste-t-il ?",
  i13_e: "Neuf bonbons, moins les trois que tu as mangés : il en reste six.",
  i14_c: "Tom a sept cartes. Léa a trois cartes de plus que Tom. Combien de cartes a Léa ?",
  i14_e: "Léa a trois cartes de plus que Tom : sept plus trois, ça fait dix cartes.",
  i15_c: "Écoute bien : deux… quatre… six… Quel nombre vient après ?",
  i15_e: "On avance de deux en deux : deux, quatre, six, huit.",

  // --- Séances d'entraînement : cadre ---
  accueil_seance: "Ton jeu du jour t'attend. Touche le bouton vert pour commencer.",
  seance_intro: "C'est parti pour le jeu du jour. Écoute bien chaque question, et prends ton temps.",
  seance_fin: "Bravo, le jeu du jour est fini ! Tu as bien réfléchi. Tu peux aller le dire à un grand.",

  // --- Parcours C, séance 1 ---
  c1_01_c: "Regarde la boîte. Combien de cases sont pleines ?",
  c1_01_e: "Une ligne de cinq, et encore deux : six, sept. Il y a sept cases pleines.",
  c1_02_c: "Il faut cinq bonbons. Il y en a déjà trois. Combien en manque-t-il ?",
  c1_02_e: "Trois bonbons, plus deux bonbons, ça fait cinq. Il en manque deux.",
  c1_03_c: "Il faut six étoiles. Il y en a déjà quatre. Combien en manque-t-il ?",
  c1_03_e: "Quatre étoiles, plus deux étoiles, ça fait six. Il en manque deux.",
  c1_04_c: "Chaque grande barre a dix cubes. Compte d'abord les barres, de dix en dix, puis les petits cubes. Combien y a-t-il de cubes en tout ?",
  c1_04_e: "Dix, vingt : deux barres. Puis vingt et un, vingt-deux, vingt-trois, vingt-quatre. Il y a vingt-quatre cubes.",
  c1_05_c: "Il faut sept billes. Il y en a déjà quatre. Combien en manque-t-il ?",
  c1_05_e: "Quatre billes, plus trois billes, ça fait sept. Il en manque trois.",
  c1_06_c: "Combien font cinq plus deux ?",
  c1_06_e: "Cinq, et encore deux : six, sept. Cinq plus deux égale sept.",
  c1_07_c: "Combien y a-t-il de cubes en tout ? Compte d'abord les barres de dix.",
  c1_07_e: "Dix, vingt, trente : trois barres. Plus cinq petits cubes : trente-cinq.",
  c1_08_c: "On veut cinq images. On en a déjà quatre. Combien faut-il en ajouter ?",
  c1_08_e: "Quatre, et encore un : cinq. Il faut en ajouter un. Quatre plus un égale cinq.",
  c1_09_c: "Écoute : quatre-vingt-sept, quatre-vingt-huit, quatre-vingt-neuf… Quel nombre vient après ? Tape-le.",
  c1_09_e: "Après quatre-vingt-neuf, il y a quatre-vingt-dix. On écrit le chiffre neuf, puis le chiffre zéro : neuf barres de dix.",
  c1_10_c: "Fabrique le nombre vingt-six. Le bouton plus, à gauche, ajoute une grande barre de dix. Le bouton plus, à droite, ajoute un petit cube. Quand tu as fini, touche le bouton vert.",
  c1_10_e: "Vingt-six, c'est deux barres de dix, et six petits cubes.",
  c1_11_c: "Tu as quatre billes. On t'en donne deux. Combien de billes as-tu maintenant ?",
  c1_11_e: "Quatre billes, plus deux billes : ça fait six billes.",
  c1_12_c: "Il faut six cartes. Il y en a déjà deux. Combien en manque-t-il ?",
  c1_12_e: "Deux cartes, plus quatre cartes, ça fait six. Il en manque quatre.",
  c1_13_c: "Touche le nombre le plus grand.",
  c1_13_e: "Quarante-deux a quatre dizaines. Vingt-quatre n'en a que deux. Le plus grand, c'est quarante-deux.",
  c1_14_c: "Tu as sept bonbons. Tu en donnes deux à un ami. Combien de bonbons te reste-t-il ?",
  c1_14_e: "Sept bonbons, moins les deux que tu as donnés : il en reste cinq.",
  c1_15_c: "On veut sept bonbons. On en a déjà cinq. Combien faut-il en ajouter ?",
  c1_15_e: "Cinq, puis six, sept : il faut en ajouter deux. Cinq plus deux égale sept.",

  // --- Parcours C, séance 2 ---
  c2_01_c: "La boîte a dix cases. Combien de cases sont vides ?",
  c2_01_e: "Huit cases sont pleines. Il reste deux cases vides. Huit plus deux égale dix.",
  c2_02_c: "Combien de cases faut-il encore remplir, pour que la boîte soit pleine ?",
  c2_02_e: "Sept cases sont pleines. Il en faut encore trois. Sept plus trois égale dix.",
  c2_03_c: "Il faut huit étoiles. Il y en a déjà cinq. Combien en manque-t-il ?",
  c2_03_e: "Cinq étoiles, plus trois étoiles, ça fait huit. Huit, c'est cinq plus trois.",
  c2_04_c: "Combien y a-t-il de cubes en tout ? Compte d'abord les barres de dix.",
  c2_04_e: "Dix, vingt, trente, quarante, cinquante : cinq barres. Plus deux petits cubes : cinquante-deux.",
  c2_05_c: "Quatre, plus combien, égale dix ? Regarde les cases vides de la boîte.",
  c2_05_e: "Il y a six cases vides. Quatre plus six égale dix.",
  c2_06_c: "On veut neuf billes. On en a déjà cinq. Combien faut-il en ajouter ?",
  c2_06_e: "Cinq, puis six, sept, huit, neuf : il faut en ajouter quatre. Cinq plus quatre égale neuf.",
  c2_07_c: "Écoute : quatre-vingt-huit, quatre-vingt-neuf, quatre-vingt-dix… Quel nombre vient après ? Tape-le.",
  c2_07_e: "Après quatre-vingt-dix, il y a quatre-vingt-onze. On écrit le chiffre neuf, puis le chiffre un : neuf barres de dix, et un petit cube.",
  c2_08_c: "Combien font trois plus quatre ?",
  c2_08_e: "Trois, et encore quatre : quatre, cinq, six, sept. Trois plus quatre égale sept.",
  c2_09_c: "Fabrique le nombre quarante-trois, avec les barres de dix et les petits cubes. Quand tu as fini, touche le bouton vert.",
  c2_09_e: "Quarante-trois, c'est quatre barres de dix, et trois petits cubes.",
  c2_10_c: "Il y a huit cartes. Tom en prend trois. Combien de cartes reste-t-il ?",
  c2_10_e: "Huit cartes, moins les trois que Tom a prises : il en reste cinq.",
  c2_11_c: "On veut huit étoiles. On en a déjà six. Combien faut-il en ajouter ?",
  c2_11_e: "Six, puis sept, huit : il faut en ajouter deux. Six plus deux égale huit.",
  c2_12_c: "Voici quarante-sept. Combien y a-t-il de grandes barres de dix ?",
  c2_12_e: "Quarante-sept, c'est quatre barres de dix, et sept petits cubes. Le premier chiffre, quatre, dit combien il y a de barres.",
  c2_13_c: "Léa a cinq étoiles. Elle en gagne quatre. Combien d'étoiles a-t-elle maintenant ?",
  c2_13_e: "Cinq étoiles, plus quatre étoiles : ça fait neuf étoiles.",
  c2_14_c: "Touche le nombre le plus petit.",
  c2_14_e: "Cinquante-cinq et cinquante-sept ont tous les deux cinq dizaines. Cinquante-cinq a moins de petits cubes : c'est le plus petit.",
  c2_15_c: "Dix, c'est trois plus combien ? Regarde les cases vides de la boîte.",
  c2_15_e: "Il y a sept cases vides. Dix, c'est trois plus sept.",

  // --- Parcours C, séance 3 ---
  c3_01_c: "Cinq, plus combien, égale dix ?",
  c3_01_e: "Cinq plus cinq égale dix. La boîte a deux lignes de cinq.",
  c3_02_c: "Huit, c'est cinq plus combien ? Tu peux t'aider de tes doigts : montre cinq doigts, puis ajoute des doigts jusqu'à huit.",
  c3_02_e: "Cinq, puis six, sept, huit : on a ajouté trois. Huit, c'est cinq plus trois.",
  c3_03_c: "Combien y a-t-il de cubes en tout ?",
  c3_03_e: "Dix, vingt, trente, quarante, cinquante, soixante. Six barres de dix, et pas de petit cube : soixante.",
  c3_04_c: "Neuf, c'est sept plus combien ?",
  c3_04_e: "Sept, puis huit, neuf : on a ajouté deux. Neuf, c'est sept plus deux.",
  c3_05_c: "Écoute bien le nombre, puis tape-le : quatre-vingt-quinze.",
  c3_05_e: "Quatre-vingt-quinze, c'est neuf barres de dix, et cinq petits cubes. On écrit le chiffre neuf, puis le chiffre cinq.",
  c3_06_c: "Combien font six plus deux ?",
  c3_06_e: "Six, et encore deux : sept, huit. Six plus deux égale huit.",
  c3_07_c: "Léa veut dix étoiles. Elle en a déjà sept. Combien d'étoiles lui manque-t-il ?",
  c3_07_e: "Sept étoiles, plus trois étoiles, ça fait dix. Il lui en manque trois.",
  c3_08_c: "Fabrique le nombre trente-huit, avec les barres de dix et les petits cubes. Quand tu as fini, touche le bouton vert.",
  c3_08_e: "Trente-huit, c'est trois barres de dix, et huit petits cubes.",
  c3_09_c: "Sept, c'est trois plus combien ? Tu peux t'aider de tes doigts.",
  c3_09_e: "Trois, puis quatre, cinq, six, sept : on a ajouté quatre. Sept, c'est trois plus quatre.",
  c3_10_c: "Touche le nombre le plus grand.",
  c3_10_e: "Quatre-vingt-seize a neuf dizaines. Soixante-neuf n'en a que six. Le plus grand, c'est quatre-vingt-seize.",
  c3_11_c: "Tu as dix billes. Tu en perds quatre. Combien de billes te reste-t-il ?",
  c3_11_e: "Dix billes, moins les quatre perdues : il en reste six.",
  c3_12_c: "Combien font quatre plus six ?",
  c3_12_e: "Quatre plus six égale dix. C'est comme six plus quatre : la boîte est pleine.",
  c3_13_c: "Voici cinquante-huit. Combien y a-t-il de petits cubes, à côté des barres ?",
  c3_13_e: "Cinquante-huit, c'est cinq barres de dix, et huit petits cubes. Le deuxième chiffre, huit, dit combien il y a de petits cubes.",
  c3_14_c: "Tom a cinq cartes. Léa a deux cartes de plus que Tom. Combien de cartes a Léa ?",
  c3_14_e: "Léa a autant de cartes que Tom, et encore deux. Cinq plus deux, ça fait sept cartes.",
  c3_15_c: "Dix, c'est six plus combien ?",
  c3_15_e: "Six, puis sept, huit, neuf, dix : on a ajouté quatre. Dix, c'est six plus quatre.",

  // --- Parcours N, séance 1 ---
  n1_01_c: "Écoute : quatre-vingt-sept, quatre-vingt-huit, quatre-vingt-neuf… Quel nombre vient juste après ?",
  n1_01_e: "Après quatre-vingt-neuf, il y a quatre-vingt-dix : neuf barres de dix.",
  n1_02_c: "Quel nombre vient juste après quatre-vingt-quatorze ?",
  n1_02_e: "Après quatre-vingt-quatorze, il y a quatre-vingt-quinze.",
  n1_03_c: "Attention, écoute bien. Quel nombre vient juste avant quatre-vingt-dix ?",
  n1_03_e: "Juste avant quatre-vingt-dix, il y a quatre-vingt-neuf. Avant, c'est un de moins.",
  n1_04_c: "Combien y a-t-il de cubes en tout ?",
  n1_04_e: "Neuf barres de dix, ça fait quatre-vingt-dix. Plus trois petits cubes : quatre-vingt-treize.",
  n1_05_c: "Écoute bien le nombre, puis tape-le : quatre-vingt-dix-sept.",
  n1_05_e: "Quatre-vingt-dix-sept, c'est neuf barres de dix, et sept petits cubes. On écrit le chiffre neuf, puis le chiffre sept.",
  n1_06_c: "Fabrique le nombre soixante-seize, avec les barres de dix et les petits cubes. Quand tu as fini, touche le bouton vert.",
  n1_06_e: "Soixante-seize, c'est sept barres de dix, et six petits cubes : soixante-dix, et encore six.",
  n1_07_c: "Tom a six billes. Léa a quatre billes de plus que Tom. Combien de billes a Léa ?",
  n1_07_e: "Léa a autant de billes que Tom, et encore quatre. Six plus quatre, ça fait dix billes.",
  n1_08_c: "Combien font quarante plus trente ?",
  n1_08_e: "Quatre barres de dix, plus trois barres de dix : sept barres. Quarante plus trente égale soixante-dix.",
  n1_09_c: "Un ami a calculé huit plus cinq, et il a trouvé douze. Vérifie. Quel est le bon résultat ?",
  n1_09_e: "Huit, plus deux pour faire dix, plus encore trois : treize. Huit plus cinq égale treize.",
  n1_10_c: "Touche le nombre le plus grand.",
  n1_10_e: "Quatre-vingt-dix-sept a neuf dizaines. C'est le plus grand.",
  n1_11_c: "Léa a neuf cartes. Tom a trois cartes de moins que Léa. Combien de cartes a Tom ?",
  n1_11_e: "Tom en a moins que Léa : on enlève trois. Neuf moins trois, ça fait six cartes.",
  n1_12_c: "Voici une ligne qui va de zéro à cent. Touche l'endroit où se trouve quatre-vingt-dix.",
  n1_12_e: "Quatre-vingt-dix est tout près de cent : il ne manque que dix.",
  n1_13_c: "Combien font quarante-sept plus dix ?",
  n1_13_e: "Plus dix, on ajoute une barre de dix : quarante-sept, cinquante-sept. Quarante-sept plus dix égale cinquante-sept.",
  n1_14_c: "Écoute : quatre-vingt-quinze, quatre-vingt-dix, quatre-vingt-cinq… Quel nombre vient après ?",
  n1_14_e: "On recule de cinq en cinq : quatre-vingt-quinze, quatre-vingt-dix, quatre-vingt-cinq, quatre-vingts.",
  n1_15_c: "Il y a douze bonbons. On en mange cinq. Combien de bonbons reste-t-il ?",
  n1_15_e: "Douze bonbons, moins les cinq mangés : il en reste sept.",

  // --- Parcours N, séance 2 ---
  n2_01_c: "Quel nombre vient juste après quatre-vingt-dix-neuf ?",
  n2_01_e: "Après quatre-vingt-dix-neuf, il y a cent. Cent, c'est dix barres de dix. On l'écrit avec trois chiffres : un, zéro, zéro.",
  n2_02_c: "Écoute bien le nombre, puis tape-le : soixante-quatorze.",
  n2_02_e: "Soixante-quatorze, c'est sept barres de dix, et quatre petits cubes. On écrit le chiffre sept, puis le chiffre quatre.",
  n2_03_c: "Attention, regarde bien les petits cubes. Combien y a-t-il de cubes en tout ?",
  n2_03_e: "Trois barres, ça fait trente. Douze petits cubes, c'est encore une barre de dix et deux cubes. Trente plus douze égale quarante-deux.",
  n2_04_c: "Fabrique le nombre soixante, avec les barres de dix et les petits cubes. Quand tu as fini, touche le bouton vert.",
  n2_04_e: "Soixante, c'est six barres de dix, et aucun petit cube.",
  n2_05_c: "Combien font neuf plus six ?",
  n2_05_e: "Neuf, plus un pour faire dix, plus encore cinq : quinze. Neuf plus six égale quinze.",
  n2_06_c: "Tom a quinze billes. Léa a cinq billes de plus que Tom. Combien de billes a Léa ?",
  n2_06_e: "Léa a autant de billes que Tom, et encore cinq. Quinze plus cinq, ça fait vingt billes.",
  n2_07_c: "Combien font soixante-dix moins vingt ?",
  n2_07_e: "Sept barres de dix, moins deux barres : il reste cinq barres. Soixante-dix moins vingt égale cinquante.",
  n2_08_c: "Soixante-quatre, c'est soixante plus combien ?",
  n2_08_e: "Soixante-quatre, c'est six barres de dix, et quatre petits cubes. Soixante-quatre, c'est soixante plus quatre.",
  n2_09_c: "Un ami a calculé quarante plus cinq, et il a trouvé quatre-vingt-dix. Vérifie. Quel est le bon résultat ?",
  n2_09_e: "Quarante, ce sont quatre barres. Cinq, ce sont cinq petits cubes, pas des barres. Quarante plus cinq égale quarante-cinq.",
  n2_10_c: "Tu as cinq billes. On t'en donne quatre. Puis tu en perds deux. Combien de billes as-tu maintenant ?",
  n2_10_e: "Cinq plus quatre, ça fait neuf. Puis neuf moins deux, ça fait sept billes.",
  n2_11_c: "Touche le nombre le plus petit.",
  n2_11_e: "Soixante-six et soixante-huit ont six dizaines. Soixante-six a moins de petits cubes : c'est le plus petit.",
  n2_12_c: "Voici une ligne qui va de zéro à cent. Touche l'endroit où se trouve vingt-cinq.",
  n2_12_e: "Vingt-cinq est au milieu, entre zéro et cinquante.",
  n2_13_c: "Léa a vingt cartes. Tom a quatre cartes de moins que Léa. Combien de cartes a Tom ?",
  n2_13_e: "Tom en a moins que Léa : on enlève quatre. Vingt moins quatre, ça fait seize cartes.",
  n2_14_c: "Écoute : trois, six, neuf… Quel nombre vient après ?",
  n2_14_e: "On avance de trois en trois : trois, six, neuf, douze.",
  n2_15_c: "Une boîte peut contenir vingt cartes. Il y a déjà dix-sept cartes dedans. Combien de cartes peut-on encore mettre ?",
  n2_15_e: "Dix-sept, puis dix-huit, dix-neuf, vingt : on peut encore en mettre trois. Dix-sept plus trois égale vingt.",

  // --- Parcours N, séance 3 ---
  n3_01_c: "Quel nombre vient juste après soixante-dix-neuf ?",
  n3_01_e: "Après soixante-dix-neuf, il y a quatre-vingts : huit barres de dix.",
  n3_02_c: "Écoute bien le nombre, puis tape-le : quatre-vingt-onze.",
  n3_02_e: "Quatre-vingt-onze, c'est neuf barres de dix, et un petit cube. On écrit le chiffre neuf, puis le chiffre un.",
  n3_03_c: "Cinquante-deux, c'est combien plus deux ?",
  n3_03_e: "Cinquante-deux, c'est cinq barres de dix, et deux petits cubes. Cinquante-deux, c'est cinquante plus deux.",
  n3_04_c: "Combien font trente-six plus vingt ?",
  n3_04_e: "Plus vingt, on ajoute deux barres de dix : trente-six, quarante-six, cinquante-six. Trente-six plus vingt égale cinquante-six.",
  n3_05_c: "Tom a sept billes. Léa a dix billes. Combien de billes Léa a-t-elle de plus que Tom ?",
  n3_05_e: "Pour aller de sept à dix : huit, neuf, dix. Léa a trois billes de plus que Tom.",
  n3_06_c: "Fabrique le nombre quatre-vingt-cinq, avec les barres de dix et les petits cubes. Quand tu as fini, touche le bouton vert.",
  n3_06_e: "Quatre-vingt-cinq, c'est huit barres de dix, et cinq petits cubes.",
  n3_07_c: "Un ami a calculé cinquante plus vingt, et il a trouvé cinquante-deux. Vérifie. Quel est le bon résultat ?",
  n3_07_e: "Vingt, ce sont deux barres de dix, pas deux petits cubes. Cinq barres plus deux barres, ça fait sept barres : soixante-dix.",
  n3_08_c: "Combien font quinze moins six ?",
  n3_08_e: "Quinze moins cinq, ça fait dix. Moins encore un, ça fait neuf. Quinze moins six égale neuf.",
  n3_09_c: "Léa a douze cartes. Elle a quatre cartes de plus que Tom. Combien de cartes a Tom ?",
  n3_09_e: "C'est Léa qui en a le plus. Tom en a donc quatre de moins : douze moins quatre, ça fait huit cartes.",
  n3_10_c: "Touche le nombre le plus grand.",
  n3_10_e: "Cent vient juste après quatre-vingt-dix-neuf. Cent est le plus grand.",
  n3_11_c: "Écoute : cent, quatre-vingt-dix, quatre-vingts… Quel nombre vient après ?",
  n3_11_e: "On recule de dix en dix : cent, quatre-vingt-dix, quatre-vingts, soixante-dix.",
  n3_12_c: "Voici une ligne qui va de zéro à cent. Touche l'endroit où se trouve soixante-quinze.",
  n3_12_e: "Soixante-quinze est entre cinquante et cent, juste au milieu.",
  n3_13_c: "Dans un sac, il y a dix billes. On en ajoute quatre. Puis on en retire trois. Combien de billes y a-t-il dans le sac ?",
  n3_13_e: "Dix plus quatre, ça fait quatorze. Puis quatorze moins trois, ça fait onze billes.",
  n3_14_c: "Dans quatre-vingt-sept, combien y a-t-il de dizaines ?",
  n3_14_e: "Quatre-vingt-sept, c'est huit barres de dix, et sept petits cubes. Il y a huit dizaines.",
  n3_15_c: "Il faut cinquante points pour gagner. Tom a déjà quarante-six points. Combien de points lui manque-t-il ?",
  n3_15_e: "Quarante-six, puis quarante-sept, quarante-huit, quarante-neuf, cinquante : il lui manque quatre points."

};
